#!/bin/bash

# fo: Stands for Format.(Couldn't come up with something better 🙄)
# Simple bash script to format hard drive.
# Updated - November 2019

# set -x # Debug mode.
# set -n # Run w/o execution.

# Check CLA
if [ $# -ne 1 ]; then
	printf "\nWrong number of arguments"
	printf "\nUsage: %s disk name\n" "${0##*/}"
	exit 1
fi

#Main#
#######

# Try to display the targeted disk on the screen.
# Exit if disk is not present.
diskutil list | grep -i "$1" || {
	printf "\nDisk %s not found, task failed.\n" "$1"
	printf "Check if %s is connected and try again.\n" "$1"
	exit 2
}

# Get the disk name from CL
disk_name=$1

# Format disk or exit with error for failure.
diskutil eraseDisk JHFS+ Emptied /dev/"$disk_name" || {
	printf "\nCouldn't open %s, task failed.\n" "$1"
	exit 2
}

# display new disk volume.
diskutil list | grep -i "Emptied"

# write reuslts to stdout.
printf "\nDone\n\n"

# Unmount disk. exit with error on failure.
diskutil unmountDisk /dev/"$disk_name" || {
	printf "\nCouldn't unmount disk %s" "$1"
	exit 3
}

# write reuslts to stdout.
printf "\n\tCompleted.\n\n"

exit 0
