#!/bin/bash

# Get the Network address
network_addr=''

system=$(uname)
if [ "$system" == "Linux" ];
then
	network_addr=$(ip route get 1.2.3.4 | awk '{print $7}' | awk -F'.' '{print $1"."$2"."$3}')
	#network_addr=$(hostname -I | cut -d' ' -f1 | awk -F'.' '{print $1"."$2"."$3}')
elif [ "$system" == "Darwin" ];
then
	network_addr=$(ipconfig getifaddr en0 | awk -F'.' '{print $1"."$2"."$3}')
fi

# Scan for live hosts.
if [ "$network_addr" != "" ];
then
	for i in $(seq 1 254); do
		ping "$network_addr"."$i" -c 1 | grep -i "64 bytes" | cut -d" " -f4 | sed 's/.$//'
	done | nl
else
	echo "Error: Issue detected with the network address."
	exit 1
fi
