#!/bin/bash

# Update :
# Simple bash script to run mac system and terminal tools update.
# Updated : November 2020

# set -x # Debug mode.
# set -n # Run w/o execution.

{
# Trap signal
trap 'echo "Cannot stop now. Give it a minute!"' SIGINT SIGTERM SIGTSTP 

printf "\nHello Dede.\n"

# Mac App Store applications update.
printf "\nStarting Mac Appstore Apps update ...\n"
mas upgrade

# Applications update via Brew.
printf "\nStarting Brew Cask Update ...\n"
# brew cask upgrade # deprecated
brew upgrade --cask

# Brew packages update.
printf "\nStartting Brew packages update and upgrade ...\n"
brew upgrade && brew update

# Mac Operating system update.
printf "\nStarting MacOS Update ...\n"
printf "Please provide system "
sudo softwareupdate -iaR --verbose

}
exit 0
