#!/bin/bash

set -euo pipefail

# Update :
# Simple bash script to update macOS and utils.
# Usage :  run "update os" or "update tools" || "update"
# Updated : November 2020

# set -x # Debug mode.
# set -n # Run w/o execution.

macOS_updater(){
    # Mac Operating system update.
    printf "\n\33[32m[+]\33[0m Starting MacOS Update ...\n"
    #printf "[+] Please provide system "
    # sudo softwareupdate -iaR --verbose
    sudo softwareupdate --all --install --force --verbose --restart
    printf "\n\n"
}


utils_runner(){
    {   
        { # Trap Signal TODO : Improvement needed here
            trap 'printf "\t\33[31m[✘]\33[0m Caught Signal"' SIGINT SIGTERM SIGTSTP 

        # brew doctor # TODO
        if [ "$SYSTEM" == "Darwin" ];
        then 
            # Mac App Store applications update.
            printf "\n[+] Starting Mac Appstore Apps update ...\n"
            #mas upgrade
            /usr/local/bin/mas upgrade
        fi 

        # Applications update via Brew.
        printf "\n[+] Starting Brew Cask Update ...\n"
        # brew cask upgrade # NOTE deprecated
        #brew upgrade --cask
        /home/linuxbrew/.linuxbrew/bin/brew upgrade --cask

        # Brew packages update.
        printf "\n[+] Startting Brew packages update and upgrade ...\n"
        #brew upgrade && brew update
        #/usr/local/bin/brew update && /usr/local/bin/brew upgrade
        /home/linuxbrew/.linuxbrew/bin/brew update && /home/linuxbrew/.linuxbrew/bin/brew upgrade

    } && {
        printf "\n\33[32m[✔]\33[0m Utils update completed successfully !!!\n"
            return 0
        }
}
}


main()
{
    local SYSTEM
    SYSTEM=$(uname -a | cut -d" " -f1) 
    if [ "$#" -gt "1" ]; then
        printf "\t\33[31m[✘]\33[0m Too many arguments!!!\n"
        exit 1
    elif [ "$#" -eq '0' ]; then 
        utils_runner; exit 0
    elif [ "$#" -eq '1' ]; then
        if [ "$1" == "os" ]; then
            if [ "$SYSTEM" == "Darwin" ]; then
                macOS_updater; exit 0
            elif [ "$SYSTEM" == "Linux" ]; then
                sudo apt update && sudo apt upgrade -y; exit 0
            elif [ "$1" == "tools" ]; then
                utils_runner; exit 0
            else
                cmd=$(which "$0" | awk -F '/' '{print $NF}')
                printf "\t\33[31m[✘]\33[0m Wrong option! Usage: '%s os/tools' or just '%s'\n\n" "$cmd" "$cmd"
                exit 2
            fi
        fi
    fi

    # NOTE : logic not efficient wit OS update.
    # Keep here for upcoming feature.
    if [ "$#" -eq '2' ]; then
        if [ "$1" == "os" ] && [ "$2" == "tools" ] \
            || [ "$1" == "tools" ] || [ "$2" == "os" ]
                then
                    macOS_updater && utils_runner; exit 0
                else
                    local cmd
                    #"$cmd"="$(which "$0" | awk -F '/' '{print $NF}')"
                    printf "\t\33[31m[✘]\33[0m Wrong option, usage: '%s' or just '%s'\n", "$cmd" "$cmd"
                    exit 3
        fi
    fi
}


### MAIN:
main "$@"
