#!/bin/bash

# Update :
# Simple bash script to update macOS and utils.
# Usage :  run "update os" or "update tools" || "update"
# Updated : November 2020

# set -x # Debug mode.
# set -n # Run w/o execution.

main(){
    if [ "$#" -gt '1' ] 
    then
        printf "\t\33[31m[✘]\33[0m Too many arguments!!!\n"
        exit 1
    fi

    while [ "$#" -eq '0' ] 
    do 
        utils_runner
        exit 0
    done

    while [ "$#" -eq '1' ]
    do
        if [ "$1" == "os" ] 
        then
            macOS_updater 
            exit 0
        elif [ "$1" == "tools" ]
        then
            utils_runner
            exit 0
        else
            local cmd
            "$cmd"="$(which "$0" | awk -F '/' '{print $NF}')"
            printf "\t\33[31m[✘]\33[0m Wrong option, usage: '%s' or just '%s'\n", "$cmd" "$cmd"
            exit 2
        fi
    done

    # NOTE : below logic not efficient wit OS update.
    # Kept here for posible upcoming features.
    while [ "$#" -eq '2' ]
    do
        if [ "$1" == "os" ] && [ "$2" == "tools" ] \
            || [ "$1" == "tools" ] || [ "$2" == "os" ]
                then
                    macOS_updater && utils_runner
                    exit 0
                else
                    local cmd
                    "$cmd"="$(which "$0" | awk -F '/' '{print $NF}')"
                    printf "\t\33[31m[✘]\33[0m Wrong option, usage: '%s' or just '%s'\n", "$cmd" "$cmd"
                    exit 3
        fi
    done
}


macOS_updater(){
    # Mac Operating system update.
    printf "\n\33[32m[+]\33[0m Starting MacOS Update ...\n"
    printf "[+] Please provide system "
    printf "\n\n"
    # sudo softwareupdate -iaR --verbose
    sudo softwareupdate --all --install --force --verbose --restart
}


utils_runner(){
    {   
        { # Trap Signal TODO : Improvement needed here
            trap 'printf "\t\33[31m[✘]\33[0m Caught Signal"' SIGINT SIGTERM SIGTSTP 

        # brew doctor # TODO
        # Mac App Store applications update.
        printf "\n[+] Starting Mac Appstore Apps update ...\n"
        mas upgrade

        # Applications update via Brew.
        printf "\n[+] Starting Brew Cask Update ...\n"
        # brew cask upgrade # NOTE deprecated
        brew upgrade --cask

        # Brew packages update.
        printf "\n[+] Startting Brew packages update and upgrade ...\n"
        brew upgrade && brew update
    } && {
        printf "\n\33[32m[✔]\33[0m Utils update completed successfully !!!\n"
            return 0
        }
}
}


### MAIN:
main "$@"
